In [1]:
import pandas as pd
first = pd.read_csv('10000_apply.csv')

In [2]:
second = pd.read_csv('20000_apply.csv')

In [3]:
third = pd.read_csv('30000_apply.csv')

In [4]:
forth = pd.read_csv('40000_apply.csv')

In [5]:
fifth = pd.read_csv('50000_apply.csv')

In [6]:
sixth = pd.read_csv('60000_apply.csv')

In [7]:
seventh = pd.read_csv('70000_apply.csv')

In [8]:
eighth = pd.read_csv('80000_apply.csv')

In [9]:
nineth = pd.read_csv('90000_apply.csv')

In [10]:
tenth = pd.read_csv('100000_apply.csv')

In [11]:
eleven = pd.read_csv('110000_apply.csv')

In [14]:
last = pd.read_csv('last_apply.csv')

In [15]:
all_apply = pd.concat([first,second,third,forth,fifth,sixth,seventh,eighth,nineth,tenth,eleven,last],axis=0)

In [17]:
all_apply.drop(['id','Unnamed: 0'], axis=1)

,apply_male_ratio,apply_major_一般商業學類,apply_major_一般數學相關,apply_major_不拘,apply_major_中醫學系,apply_major_人力資源相關,apply_major_人類學相關,apply_major_企業管理相關,apply_major_儀容服務學類,apply_major_光電工程相關,...,apply_cert_高考藥師,apply_cert_高考語言治療師,apply_cert_高考諮商心理師,apply_cert_高考護理師執照,apply_cert_高考都市計畫技師,apply_cert_高考醫事放射師,apply_cert_高考醫師(一),apply_cert_高考醫師(二),apply_cert_高考電機工程技師,apply_cert_高考食品技師
0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.1111,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
1,0.0,0.0,0.0,0.1667,0.0,0.0,0.0,0.1667,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
2,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
3,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
4,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.2000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23010,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
23011,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
23012,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
23013,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
23014,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0

In [18]:
all_apply.to_csv('all_apply.csv')

In [19]:
without_apply_x_fina_standard = pd.read_csv('without_apply_x_fina_standard.csv')

In [23]:
without_apply_x_fina_standard.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1)

,appearDate,enviornmentPic,driverLicense,other,welfare,jobDescription,manageResp,businessTrip,workPeriod,edu_不拘,...,major_其他,language_其他,specialty_其他,skill_其他,certificate_其他,jobCategory_其他,adressArea_其他,vacationPolicy_其他,startWorkingDay_其他,industry_其他
0,11,4,0,0.866432,0.148969,1.079455,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,12,0,1,5.432469,-0.309059,2.258925,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,13,4,0,0.348825,-0.513967,-0.530362,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,14,0,0,-0.057867,-0.706821,-0.450668,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,15,7,0,0.385797,-0.797221,-0.333783,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133010,9,0,1,0.810974,-0.495887,1.520428,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
133011,8,4,0,-0.520016,0.570838,2.046408,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
133012,11,0,0,-0.520016,-0.923782,-0.838512,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
133013,11,0,1,-0.520016,-0.923782,-0.025634,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
133014,10,0,0,-0.520016,-0.712848,0.054060,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
without_apply_x_fina_standard = without_apply_x_fina_standard.reset_index(drop=True)

In [26]:
all_apply = all_apply.reset_index(drop=True)

In [27]:
final_x = pd.concat([without_apply_x_fina_standard, all_apply],axis=1)

In [29]:
final_x.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1)

,appearDate,enviornmentPic,driverLicense,other,welfare,jobDescription,manageResp,businessTrip,workPeriod,edu_不拘,...,apply_cert_高考藥師,apply_cert_高考語言治療師,apply_cert_高考諮商心理師,apply_cert_高考護理師執照,apply_cert_高考都市計畫技師,apply_cert_高考醫事放射師,apply_cert_高考醫師(一),apply_cert_高考醫師(二),apply_cert_高考電機工程技師,apply_cert_高考食品技師
0,11,4,0,0.866432,0.148969,1.079455,1,0,1,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
1,12,0,1,5.432469,-0.309059,2.258925,1,0,1,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
2,13,4,0,0.348825,-0.513967,-0.530362,1,0,0,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
3,14,0,0,-0.057867,-0.706821,-0.450668,1,0,0,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
4,15,7,0,0.385797,-0.797221,-0.333783,1,1,0,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133010,9,0,1,0.810974,-0.495887,1.520428,1,0,1,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
133011,8,4,0,-0.520016,0.570838,2.046408,1,1,1,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
133012,11,0,0,-0.520016,-0.923782,-0.838512,1,0,0,1,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
133013,11,0,1,-0.520016,-0.923782,-0.025634,1,0,0,0,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0
133014,10,0,0,-0.520016,-0.712848,0.054060,1,1,0,1,...,0.0,0,0.0,0.0,0,0.0,0,0,0,0.0

In [ ]:
final_x.to_csv('final_x.csv')